# Generated by Django 5.0.6 on 2024-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(default=1, verbose_name='Периодичность выполнения привычки(кол-во дней)'),
        ),
    ]
